### ISSUE TITLE
BUT How to use???

### ISSUE THREAD

**Issue by BlueEve04** [amaralani/AnsiToUTF8#1]
Can it run on RPi4??
OR HOW I CAN MAKE IT WORK ?

**Comment by amaralani** [comment]
I don't know about RPi4.
To run it you should clone the project. You can run this with arguments or with UI.
Go to `/bin` and run `java Application`. 

- If no arguments are provided it runs the UI. 
- If you run `java Application no-ui /path/to/file` the application converts the provided file without UI.

You can change or re-build the project obviously.

**Comment by BlueEve04** [comment]
Thank you very much.
As I am a green hand on Raspberry PI 4.
I didn't know very well of the filesystem of Linux.
And your reply is of great help.
